version: "3.7"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - /var/lib/postgresql/data
        ports:
            - "5432:5432"
    web:
        build: ./packages/backend
        volumes:
            - ./packages/backend:/usr/src/app
            - /usr/src/app/node_modules
        restart: always
        depends_on:
            - db
        ports:
            - "${SERVER_PORT}:4000"
    adminer:
        image: adminer
        restart: always
        ports:
            - "${ADMINER_PORT}:8080"
    fe-dev:
        tty: true
        build: ./packages/frontend
        volumes:
            - ./packages/frontend:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
