// EDIT MODE
export const TOGGLE_EDIT = 'TOGGLE_EDIT';

// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// RESOURCES
export const RESOURCES_SUCCESS = 'RESOURCES_SUCCESS';
export const RESOURCES_ERROR = 'RESOURCES_ERROR';
export const REQUEST_RESOURCES = 'REQUEST_RESOURCES';
export const RECEIVE_RESOURCES = 'RECEIVE_RESOURCES';
