// EDIT MODE
export const TOGGLE_EDIT = 'TOGGLE_EDIT';
export const DISABLE_EDIT = 'DISABLE_EDIT';

// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// RESOURCES
export const FETCH_RESOURCES_START = 'FETCH_RESOURCES_START';
export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS';
export const FETCH_RESOURCES_ERROR = 'FETCH_RESOURCES_ERROR';

// VALIDATION
export const SET_DATE = 'SET_DATE';
export const SET_TARGET_DATE = 'SET_TARGET_DATE';
export const SET_TARGET_NPS = 'SET_TARGET_NPS';
export const SET_NPS = 'SET_NPS';
export const MISSING_FIELDS = 'MISSING_FIELDS';
