// EDIT MODE
export const TOGGLE_EDIT = 'TOGGLE_EDIT';
export const DISABLE_EDIT = 'DISABLE_EDIT';

// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// RESOURCES
export const FETCH_RESOURCES_START = 'FETCH_RESOURCES_START';
export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS';
export const FETCH_RESOURCES_ERROR = 'FETCH_RESOURCES_ERROR';
